### ISSUE TITLE
Updating AS relationship files makes ip2as.py crash

### ISSUE THREAD

**Issue by weiyz23** [alexmarder/ip2as#2]
Dear Alex,

Thanks for sharing your tool, too! I came across this problem in ip2as.py.

the format before:
```
1239|39386|-1
1239|39947|-1
1239|40002|-1
1239|40026|-1
1239|40032|-1
```

the format now:
```
42|6805|0|bgp
42|6894|0|bgp
42|6908|0|bgp
42|6939|0|bgp
42|7195|0|bgp
42|7489|0|bgp
```

Seems that just a llittle change can fix this bug.

Regards,
FengLan

**Comment by weiyz23** [comment]
Error message is below:

Traceback (most recent call last):
  File "/usr/local/bin/ip2as", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ip2as/ip2as.py", line 122, in main
    bgp = BGP(args.rels, args.cone)
  File "traceutils2/bgp/bgp.pyx", line 19, in traceutils2.bgp.bgp.BGP.__init__
  File "traceutils2/bgp/bgp.pyx", line 22, in traceutils2.bgp.bgp.BGP.__init__
ValueError: invalid literal for int() with base 10: 'bgp'
